apiVersion: v1
kind: Service
metadata:
  name: external-scaler-service
  namespace: oms
spec:
  selector:
    app: external-scaler
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
